/**
 * Turns a TTF into a TS module holding a base64 string so jsPDF can embed the
 * font. Reading the file from disk at runtime would depend on Vercel's file
 * tracing picking up a node_modules asset nothing imports; as a module the
 * font is bundled reliably.
 *
 * Usage: npx tsx scripts/build-font.ts node_modules/dejavu-fonts-ttf/ttf/DejaVuSans.ttf
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const quelle = process.argv[2];
if (!quelle) {
  console.error("Usage: npx tsx scripts/build-font.ts <path.ttf>");
  process.exit(1);
}

const base64 = readFileSync(quelle).toString("base64");
mkdirSync("src/lib/fonts", { recursive: true });
writeFileSync(
  "src/lib/fonts/dejaVuSans.ts",
  `// Generated by scripts/build-font.ts — do not edit by hand.\n` +
    `// DejaVu Sans Regular, Bitstream Vera license (embedding permitted).\n` +
    `// eBrief's spacing template requires fonts to be embedded completely;\n` +
    `// jsPDF's built-in Helvetica is not embedded, hence this module.\n` +
    `export const DEJAVU_SANS_REGULAR_BASE64 = "${base64}";\n`
);
console.log(`Written: src/lib/fonts/dejaVuSans.ts (${base64.length} characters)`);
